### ISSUE TITLE
Discuss multiple files entries

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus-webui#18]
Nautilus supports specifying multiple files for a single _Entry_ in the collection.json.

This ticket acknowledges this and the fact that the initial version of the webui **will not support it**.

This feature is rarely used in nautilus and exists mostly because of how the nautilus UI behaves. The most useful use-case I know is for a split audiobook with individual files per chapter.

**Comment by rgaudin** [comment]
This is being abandoned in nautilus so we don't care about it here either

**Comment by kelson42** [comment]
> This is being abandoned in nautilus so we don't care about it here either

Glad to read it, this was a small feature with significant impact in term of complexity.
