### ISSUE TITLE
Placeholder FAQ

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus-webui#3]
As for https://youzim.it/, we'll need a FAQ so we need a placeholder

**Comment by dev-adityasinha** [comment]
@rgaudin  Can you describe the issue clearly like what is the thing needed?

**Comment by rgaudin** [comment]
@dev-adityasinha I'm sorry but I can't provide usable information without looking at how things are and what we want exactly. This made sense when we were building it but that has passed now.

You better look for other tickets

**Comment by rgaudin** [comment]
Done
