### ISSUE TITLE
Contact and FAQ pages misses the Sidebar

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus-webui#50]
Has been discussed already: only home is out of sidebar.

**Comment by FledgeXu** [comment]
To be honest, I didn't quite understand what the need was here ......
CollectionView now jumps to the FAQ and Contract pages, is this behavior wrong? What we need is to display the FQA component on the type HomeView directly on the CollectionView?

**Comment by rgaudin** [comment]
Yes, once you're a returning user, you always see the sidebar. If you click on FAQ then you have sidebar on left and FAQ on the right. You don't have to go back to access the rest of the app. You can directly click on one of your project or contact.
That's the idea.

**Comment by FledgeXu** [comment]
ah, I see. So we want the FAQ and Contract to take the place of ProjectView.

**Comment by rgaudin** [comment]
Decided otherwise. There is value in having the sidebar there but it requires a significant effort. No incentive ATM
