### ISSUE TITLE
Why 1.86GB?

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus-webui#79]
Currently the FAQ (and upload screen) indicate a maximum size of 1.86 GB (actually says `We currently enforce a limit: 1.86 GB files` which reads strange and is incorrect) - this seems pretty random and the FAQ does not explain this choice.

While we're free to do as we please, it could be helpful to rephrase to something along the lines of 
_Due to technical constraints, we currently enforce a limit at 2 GB on our servers, which means up to 1.86 GB of uploadable files._ (or somesuch)

**Comment by rgaudin** [comment]
> which reads strange and is incorrect) - this seems pretty random and the FAQ does not explain this choice.

Strange, sure ; I changed it to 2GiB (we were displaying GiB as GB –jedec std– actually and the limit was set to 2GB).

Not sure what you mean by incorrect ; also FAQ wording was copied from zimit.
