### ISSUE TITLE
Unable to create arborescence

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus-webui#80]
I'm pretty sure the specs we had discussed allowing users to create/upload/have folders in our zim files but I don't see the option to upload or create such folders.

**Comment by rgaudin** [comment]
No we did not.

We did discuss supporting arborescence in nautilus (not the webui) https://github.com/openzim/nautilus/issues/43. It would need to be supported in the scraper first obviously.
Closing as it makes no sense to keep track of this while the scraper feature is not even accepted (and actually frequently contested by someone^^)
